### ISSUE TITLE
`GET /info` endpoint

### ISSUE THREAD

**Issue by foohonpie** [pbbg/pbbg.com#14]
Needed by https://github.com/pbbg/pbbg.com/issues/13:

Suggested definition:

```
  /info/{url}:
    get:
      tags:
        - "Games"
      operationId: "getInfo"
      parameters:
        - name: "url"
          in: "path"
          required: true
          schema:
            type: "string"
            example: "https://example.com"
      responses:
        "200":
          description: "response"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  valid:
                    type: "boolean"
                    example: true
                  url:
                    type: "string"
                    example: "https://example.com"
                  name:
                    type: "string"
                    example: "Example Game"
                  tags:
                    type: "string"
                    example: "foo, bar, baz"
                  short_description:
                    type: "string"
                  image_path:
                    type: "string"
                    example: "/path/toimage.jpg"
```

- [ ] `valid`

  * return `true` if the submitted url returns a valid response, otherwise return ` false`.  the actual endpoint response should be 200 either way

- [ ] `url`

  * Return canonical URL if present, otherwise return submitted URL

- [ ] `name`

  * return from meta title if present

- [ ] `short_description`

  * return from meta description if present

- [ ] `tags`

  * return from meta keywords if present

- [ ] `image_path`

  * Return an example value for now.  Returning the actual value will be handled in a separate ticket.

**Comment by krzysztof-sikorski** [comment]
The name `valid` sounds more like bool than integer.

**Comment by bpkennedy** [comment]
This will be closed in favor of the new stories coming since the dockerization of the next version of pbbg.com
