### ISSUE TITLE
Create /heartbeat endpoint

### ISSUE THREAD

**Issue by bpkennedy** [pbbg/pbbg.com#16]
I was wondering what the status of the dev-api was, as far as deploying newest code from the repo and I thought creating an endpoint like this would be helpful.

If it could tell the version of the code deployed and maybe include a hash or something - that way I can easily know.  It would also help to tell if the api is up or not, too.

**Comment by foohonpie** [comment]
A hash would be a useful build id.

Thoughts on putting this on the api root?  We could replace the current response string with something like:

```
{
  "domain": "https://dev-api.pbbg.com",
  "version": "0.1.2",
  "build": "0800fc577294c34b0b28ad2839435945",
  "links": {
    "documentation": "https://app.swaggerhub.com/apis-docs/pbbg/api.pbbg.com",
    "repository": "https://github.com/pbbg/api.pbbg.com"
  }
}
```

**Comment by bpkennedy** [comment]
That would be great.  If it's safe to do so, could we include some kind of status on Algolia?  Something that at runtime goes out and "asks if it's up/connected/ok" kinda thing.  It doesn't necessarily have to specify "which" Algolia or any private information like key/id.  This way we know if "our" server is up and we know if our Algolia instance is responding correctly, too.

**Comment by bpkennedy** [comment]
This will be closed in favor of the new stories coming since the dockerization of the next version of pbbg.com
