### ISSUE TITLE
GET /game

### ISSUE THREAD

**Issue by foohonpie** [pbbg/pbbg.com#25]
This will return a random game.

- [ ] define endpoint

- [ ] write tests

- [ ] write code

**Comment by krzysztof-sikorski** [comment]
This route feels weird, I would normally expect `/game` to be a "directory view" of all games and random game being exposed via subpath like `/game/random`.

Another question is if this should be a "full" endpoint or just fetching a random ID or slug and returning a redirection to "game details" endpoint.

**Comment by krzysztof-sikorski** [comment]
I forgot that the directory view is actually handled by Algolia search. But I still feel that using `/game` for this route is wrong, you should reserve it for future if/when you replace Algolia by some other engine, and use something like `/game/random` for getting a random game.

**Comment by foohonpie** [comment]
We do have `/games` as the list view, but yeah `/game` does feel questionable even without that issue.  `/games/random` would also cause issues if a game was actually named "Random" which is unlikely, but possible.

Maybe `/random/game` instead?  That would set us up for other resources too, like `/random/review` or `/random/user`.

As for Algolia, `/games` on the website uses it but `/games` from the API returns non-Algolia results, so I think we're ok there.  If we ever swap out to something else, our API responses shouldn't be impacted.

> Another question is if this should be a "full" endpoint or just fetching a random ID or slug and returning a redirection to "game details" endpoint.

I like the idea of it returning a full response, that way it can be re-requested repeatedly with usable results at the ready.  It'll be less work for the FE that way.

Good questions, thanks!

**Comment by bpkennedy** [comment]
This will be closed in favor of the new stories coming since the dockerization of the next version of pbbg.com
