### ISSUE TITLE
pbbg.com-docker cypress build issue on Raspberry Pi

### ISSUE THREAD

**Issue by Ratstail91** [pbbg/pbbg.com#43]
By @bpkennedy 's request, I'm opening this issue here, rather than his personal repo.

When trying to build pbbg.com-docker on my raspberry pi, it fails due to cypress. Removing cypress as a dependency allows the build to complete with only warnings. However, I still can't get it to *run* just yet; I'm still working on it. The cypress errors are below.

My pi's specs are as follows:

> Raspberry Pi 4b - 8GB ram

uname -a
> Linux raspberrypi 5.10.11-v8+ #1399 SMP PREEMPT Thu Jan 28 12:14:03 GMT 2021 aarch64 GNU/Linux

cat /etc/os-release
> PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
> NAME="Raspbian GNU/Linux"
> VERSION_ID="10"
> VERSION="10 (buster)"
> VERSION_CODENAME=buster
> ID=raspbian
> ID_LIKE=debian
> HOME_URL="http://www.raspbian.org/"
> SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
> BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

```
[5/5] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error /app/node_modules/cypress: Command failed.
Exit code: 1
Command: node index.js --exec install
Arguments: 
Directory: /app/node_modules/cypress
Output:
Installing Cypress (version: 3.8.3)

[20:43:53]  Downloading Cypress     [started]
[20:43:55]  Downloading Cypress     [failed]
[20:43:55] → The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/3.8.3?platform=linux&arch=ia32
Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found

----------

Platform: linux (Raspbian - )
Cypress Version: 3.8.3
The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/3.8.3?platform=linux&arch=ia32
Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found

----------

Platform: linux (Raspbian - )
Cypress Version: 3.8.3

The command '/bin/sh -c yarn --frozen-lockfile' returned a non-zero code: 1
ERROR: Service 'frontend' failed to build

```

**Comment by bpkennedy** [comment]
Awesome, thanks!  So, maybe we can first check that your pi can hit that url that is returning a 404.

From your pi in terminal do you get a 404 response when sending a `curl https://download.cypress.io/desktop/3.8.3?platform=linux&arch=ia32` ?

**Comment by bpkennedy** [comment]
@Ratstail91 , when you get some time can you try again with the current version of `master`?  I suspect the cypress issue may still be around but I would think/hope you get nothing else.

**Comment by Ratstail91** [comment]
Following the instructions...
```
Successfully tagged pbbgcom_backend:latest

ERROR: for database  (<Service: database>, '')

ERROR: for frontend  (<Service: frontend>, '')
ERROR: Service 'frontend' failed to build
```
There's no mention of cypress this time.
I might end up having to help via a remote server or something.

**Comment by bpkennedy** [comment]
Shoot, hold up.  I broke the build last night before bed (~10 hours ago). If you got master and tried building that it would have failed for sure.

I am fixing today.  Will update here once fixed.

**Comment by bpkennedy** [comment]
Actually, if you want to checkout sha with 944632c - that was the one before I broke stuff.  :)

It should be in a buildable state at that point.

**Comment by bpkennedy** [comment]
It should be stable for you to check again, as you have time @Ratstail91 .

**Comment by Ratstail91** [comment]
Trying the site on my pi again...
Still getting the cypress error.

```
URL: https://download.cypress.io/desktop/3.8.3?platform=linux&arch=ia32
Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found
```
etc. 

I don't think they even build cypress for this platform. I don't see a package.json to even remove it from...

I don't think I can help while I'm running on this pi. I'm going to close this issue, since the only machine it really needs to run on is your server. I'm gonna focus on my stuff for now. Thanks anyway for trying!
