### ISSUE TITLE
PBBG-70 - install and configure Laravel Fortify

### ISSUE THREAD

**Issue by bpkennedy** [pbbg/pbbg.com#54]
[JIRA issue](https://pbbg.atlassian.net/browse/PBBG-70)

Technically, this story is about getting some application foundations in place for feature development.  This issue is focused on primarily the backend/api side of that.  The Laravel api is freshly scaffolded and needs:

* Fortify to be setup and ready for user account registration, login/logout (email sending not yet included, password reset not yet included).
* The current init.sql inside `/database` is a placeholder more than anything. We need whatever the proper initial db seed and first migration will be in place instead.
* The seed/migration needs to create the users table (unsure if Fortify handles on its own) and 1 test user.
* Testing is not yet required for this story - however, designing the initial seed/migration in a way that they can be rerun between individual tests will give us some good test isolation.  Whether that means we wipe the db altogether or merely truncate the tables, we need something that'll let us start fresh.
 > If this is more complex than it seems, then we can do this activity in the future story that gets testing in place.

If there's any questions or clarity needed, please ask away!  Let me know if you're planning to work on this issue and if so, I'll put you as Assigned.

**If you see someone Assigned to this issue then that means you shouldn't also be working on it without coordinating with them first as you may be duplicating work!**

**Comment by calebanthony** [comment]
I'd love to tackle this!

Just need some clarification on this:

> We need whatever the proper initial db seed and first migration will be in place instead. 

I assume this means translate the existing `init.sql` to Laravel-friendly migrations, but just wanted to confirm.

**Comment by bpkennedy** [comment]
Awesome!  Thanks!

And yep, that's more correct/precise.

**Comment by bpkennedy** [comment]
@calebanthony , I think this is about done - all we may need to do is to add in the other `php artisan` commands you were thinking for cache clearing and route cache clearing on api startup.  Just let me know if you want to add those, or I can!  Thanks.

**Comment by bpkennedy** [comment]
I'll close this, thinking we can handle the cache commands in the following stories
